version: '3'
services:
  db:
    image: cockroachdb/cockroach:v2.1.3
    hostname: cockroach
    command: start --insecure
    volumes:
      - "${PWD}/data:/cockroach/cockroach-data"
    ports:
      - 26257:26257
      - 8080:8080
